name: places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  surf_lint_rules: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - res/assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/roboto/Roboto-Black.ttf
        - asset: res/fonts/roboto/Roboto-BlackItalic.ttf
        - asset: res/fonts/roboto/Roboto-Bold.ttf
        - asset: res/fonts/roboto/Roboto-BoldItalic.ttf
        - asset: res/fonts/roboto/Roboto-Italic.ttf
        - asset: res/fonts/roboto/Roboto-Light.ttf
        - asset: res/fonts/roboto/Roboto-LightItalic.ttf
        - asset: res/fonts/roboto/Roboto-Medium.ttf
        - asset: res/fonts/roboto/Roboto-MediumItalic.ttf
        - asset: res/fonts/roboto/Roboto-Regular.ttf
        - asset: res/fonts/roboto/Roboto-Thin.ttf
        - asset: res/fonts/roboto/Roboto-ThinItalic.ttf
