name: places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  date_format: ^2.0.6
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  location: ^4.4.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  surf_lint_rules: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - res/svg/
    - res/svg/chips/
    - res/svg/onboarding/
  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: res/fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: res/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: res/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: res/fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: res/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: res/fonts/roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: res/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: res/fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: res/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: res/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: res/fonts/roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
