name: places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  date_format: ^2.0.6
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_svg: ^1.1.0
  geolocator: ^9.0.2
  image_picker: ^0.8.6
  location: ^4.4.0
  map_launcher: ^2.4.0
  path: ^1.8.1
  path_provider: ^2.0.11
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  sqlite3: ^1.8.0
  sqlite3_flutter_libs: ^0.5.12
  surf_lint_rules: ^1.5.0
  yandex_mapkit: ^3.2.0

dev_dependencies:
  build_runner: ^2.3.2
  drift_dev: ^1.7.0

  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/svg/app_icons/dev_app_icon.png"
  android: true
  ios: false

flutter:

  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/svg/app_icons/
    - assets/svg/chips/
    - assets/svg/onboarding/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
